### ISSUE TITLE
OSX 'screencapture' killed 9

### ISSUE THREAD

**Issue by fritx** [uiureo/node-screencapture#5]
![qq 20151013155017](https://cloud.githubusercontent.com/assets/6647633/10448834/1e63b7a6-71c2-11e5-8971-c8c801537ed7.jpg)

It was on an OSX 10.10.5 machine.
As I tried copying '/usr/sbin/screencapture' to '~/' and renaming it to 'sc', it worked.
I guess it is the process name 'screencapture' that would be killed.
Even 'screencapture1' would work but not 'screencapture'.

In my [fork](https://github.com/fritx/node-screencapture/commits/gt), I also included the 'sc' into bin, as well as nircmd.
However, I think it is not a very common case to be considered in master?

**Comment by uiur** [comment]
On my machine (OSX 10.10.5), it works correctly. I think there's something wrong with your environment.

> In my fork, I also included the 'sc' into bin, as weel as nircmd.

You should not. `screencapture` is under copyright of Apple.

**Comment by fritx** [comment]
Oops! Thanks for reminding.. I wonder what would I do to solve this issue.

**Comment by fritx** [comment]
OK. Maybe I won't publish the `sc` but use it, copying it by npm postinstall. Is it gonna solve the copyright issue?

**Comment by uiur** [comment]
I think so.

**Comment by fritx** [comment]
Thanks!

**Comment by fritx** [comment]
Sorry for the late report, it was killed by some security software in our office,
and had nothing to do with node-screencapture.

**Comment by uiur** [comment]
> Sorry for the late report, it was killed by some security software in our office,

😿
