### ISSUE TITLE
[question] Screencapture on multiple monitors?

### ISSUE THREAD

**Issue by fritx** [uiureo/node-screencapture#8]
I'm not familiar with `screencapture` in OSX.
I wonder is it able to capture full shots within more than one monitors (screens).

Btw, in Windows, the `nircmd` does support this feature,
see https://github.com/fritx/node-screencapture/blob/gt/lib/capture_exec.js#L14

**Comment by uiur** [comment]
I think you can. I'll make sure it works tomorrow, because I don't have any monitors now.

**Comment by uiur** [comment]
@fritx Sorry for slow reply.
The answer is yes. `screencapture` is able to capture multiple screens.

**Comment by fritx** [comment]
Thanks! That's awesome :+1:
